// Code generated by ent, DO NOT EDIT.

package attribute

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the attribute type in the database.
	Label = "attribute"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldValueType holds the string denoting the value_type field in the database.
	FieldValueType = "value_type"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldValueDescription holds the string denoting the value_description field in the database.
	FieldValueDescription = "value_description"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// Table holds the table name of the attribute in the database.
	Table = "attributes"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "attributes"
	// OwnerInverseTable is the table name for the Product entity.
	// It exists in this package in order to avoid circular dependency with the "product" package.
	OwnerInverseTable = "products"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "product_attributes"
)

// Columns holds all SQL columns for attribute fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldValueType,
	FieldValue,
	FieldValueDescription,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "attributes"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"product_attributes",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Attribute queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByValueType orders the results by the value_type field.
func ByValueType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValueType, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByValueDescription orders the results by the value_description field.
func ByValueDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValueDescription, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
	)
}
