// Code generated by ent, DO NOT EDIT.

package product

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the product type in the database.
	Label = "product"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPhoto holds the string denoting the photo field in the database.
	FieldPhoto = "photo"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// EdgeAttributes holds the string denoting the attributes edge name in mutations.
	EdgeAttributes = "attributes"
	// EdgeRates holds the string denoting the rates edge name in mutations.
	EdgeRates = "rates"
	// EdgeVectors holds the string denoting the vectors edge name in mutations.
	EdgeVectors = "vectors"
	// Table holds the table name of the product in the database.
	Table = "products"
	// AttributesTable is the table that holds the attributes relation/edge.
	AttributesTable = "attributes"
	// AttributesInverseTable is the table name for the Attribute entity.
	// It exists in this package in order to avoid circular dependency with the "attribute" package.
	AttributesInverseTable = "attributes"
	// AttributesColumn is the table column denoting the attributes relation/edge.
	AttributesColumn = "product_attributes"
	// RatesTable is the table that holds the rates relation/edge.
	RatesTable = "rates"
	// RatesInverseTable is the table name for the Rate entity.
	// It exists in this package in order to avoid circular dependency with the "rate" package.
	RatesInverseTable = "rates"
	// RatesColumn is the table column denoting the rates relation/edge.
	RatesColumn = "product_rates"
	// VectorsTable is the table that holds the vectors relation/edge.
	VectorsTable = "vectors"
	// VectorsInverseTable is the table name for the Vector entity.
	// It exists in this package in order to avoid circular dependency with the "vector" package.
	VectorsInverseTable = "vectors"
	// VectorsColumn is the table column denoting the vectors relation/edge.
	VectorsColumn = "product_vectors"
)

// Columns holds all SQL columns for product fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldPhoto,
	FieldDescription,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Product queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPhoto orders the results by the photo field.
func ByPhoto(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhoto, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByAttributesCount orders the results by attributes count.
func ByAttributesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAttributesStep(), opts...)
	}
}

// ByAttributes orders the results by attributes terms.
func ByAttributes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAttributesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRatesCount orders the results by rates count.
func ByRatesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRatesStep(), opts...)
	}
}

// ByRates orders the results by rates terms.
func ByRates(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRatesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByVectorsCount orders the results by vectors count.
func ByVectorsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVectorsStep(), opts...)
	}
}

// ByVectors orders the results by vectors terms.
func ByVectors(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVectorsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAttributesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AttributesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AttributesTable, AttributesColumn),
	)
}
func newRatesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RatesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RatesTable, RatesColumn),
	)
}
func newVectorsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VectorsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VectorsTable, VectorsColumn),
	)
}
