// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"recomCore/ent/predicate"
	"recomCore/ent/product"
	"recomCore/ent/vector"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VectorQuery is the builder for querying Vector entities.
type VectorQuery struct {
	config
	ctx        *QueryContext
	order      []vector.OrderOption
	inters     []Interceptor
	predicates []predicate.Vector
	withOwner  *ProductQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VectorQuery builder.
func (vq *VectorQuery) Where(ps ...predicate.Vector) *VectorQuery {
	vq.predicates = append(vq.predicates, ps...)
	return vq
}

// Limit the number of records to be returned by this query.
func (vq *VectorQuery) Limit(limit int) *VectorQuery {
	vq.ctx.Limit = &limit
	return vq
}

// Offset to start from.
func (vq *VectorQuery) Offset(offset int) *VectorQuery {
	vq.ctx.Offset = &offset
	return vq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vq *VectorQuery) Unique(unique bool) *VectorQuery {
	vq.ctx.Unique = &unique
	return vq
}

// Order specifies how the records should be ordered.
func (vq *VectorQuery) Order(o ...vector.OrderOption) *VectorQuery {
	vq.order = append(vq.order, o...)
	return vq
}

// QueryOwner chains the current query on the "owner" edge.
func (vq *VectorQuery) QueryOwner() *ProductQuery {
	query := (&ProductClient{config: vq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(vector.Table, vector.FieldID, selector),
			sqlgraph.To(product.Table, product.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, vector.OwnerTable, vector.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(vq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Vector entity from the query.
// Returns a *NotFoundError when no Vector was found.
func (vq *VectorQuery) First(ctx context.Context) (*Vector, error) {
	nodes, err := vq.Limit(1).All(setContextOp(ctx, vq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{vector.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vq *VectorQuery) FirstX(ctx context.Context) *Vector {
	node, err := vq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Vector ID from the query.
// Returns a *NotFoundError when no Vector ID was found.
func (vq *VectorQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vq.Limit(1).IDs(setContextOp(ctx, vq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{vector.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vq *VectorQuery) FirstIDX(ctx context.Context) int {
	id, err := vq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Vector entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Vector entity is found.
// Returns a *NotFoundError when no Vector entities are found.
func (vq *VectorQuery) Only(ctx context.Context) (*Vector, error) {
	nodes, err := vq.Limit(2).All(setContextOp(ctx, vq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{vector.Label}
	default:
		return nil, &NotSingularError{vector.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vq *VectorQuery) OnlyX(ctx context.Context) *Vector {
	node, err := vq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Vector ID in the query.
// Returns a *NotSingularError when more than one Vector ID is found.
// Returns a *NotFoundError when no entities are found.
func (vq *VectorQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vq.Limit(2).IDs(setContextOp(ctx, vq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{vector.Label}
	default:
		err = &NotSingularError{vector.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vq *VectorQuery) OnlyIDX(ctx context.Context) int {
	id, err := vq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Vectors.
func (vq *VectorQuery) All(ctx context.Context) ([]*Vector, error) {
	ctx = setContextOp(ctx, vq.ctx, "All")
	if err := vq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Vector, *VectorQuery]()
	return withInterceptors[[]*Vector](ctx, vq, qr, vq.inters)
}

// AllX is like All, but panics if an error occurs.
func (vq *VectorQuery) AllX(ctx context.Context) []*Vector {
	nodes, err := vq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Vector IDs.
func (vq *VectorQuery) IDs(ctx context.Context) (ids []int, err error) {
	if vq.ctx.Unique == nil && vq.path != nil {
		vq.Unique(true)
	}
	ctx = setContextOp(ctx, vq.ctx, "IDs")
	if err = vq.Select(vector.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vq *VectorQuery) IDsX(ctx context.Context) []int {
	ids, err := vq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vq *VectorQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, vq.ctx, "Count")
	if err := vq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, vq, querierCount[*VectorQuery](), vq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (vq *VectorQuery) CountX(ctx context.Context) int {
	count, err := vq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vq *VectorQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, vq.ctx, "Exist")
	switch _, err := vq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (vq *VectorQuery) ExistX(ctx context.Context) bool {
	exist, err := vq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VectorQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vq *VectorQuery) Clone() *VectorQuery {
	if vq == nil {
		return nil
	}
	return &VectorQuery{
		config:     vq.config,
		ctx:        vq.ctx.Clone(),
		order:      append([]vector.OrderOption{}, vq.order...),
		inters:     append([]Interceptor{}, vq.inters...),
		predicates: append([]predicate.Vector{}, vq.predicates...),
		withOwner:  vq.withOwner.Clone(),
		// clone intermediate query.
		sql:  vq.sql.Clone(),
		path: vq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (vq *VectorQuery) WithOwner(opts ...func(*ProductQuery)) *VectorQuery {
	query := (&ProductClient{config: vq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vq.withOwner = query
	return vq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Vector []byte `json:"vector,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Vector.Query().
//		GroupBy(vector.FieldVector).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (vq *VectorQuery) GroupBy(field string, fields ...string) *VectorGroupBy {
	vq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VectorGroupBy{build: vq}
	grbuild.flds = &vq.ctx.Fields
	grbuild.label = vector.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Vector []byte `json:"vector,omitempty"`
//	}
//
//	client.Vector.Query().
//		Select(vector.FieldVector).
//		Scan(ctx, &v)
func (vq *VectorQuery) Select(fields ...string) *VectorSelect {
	vq.ctx.Fields = append(vq.ctx.Fields, fields...)
	sbuild := &VectorSelect{VectorQuery: vq}
	sbuild.label = vector.Label
	sbuild.flds, sbuild.scan = &vq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VectorSelect configured with the given aggregations.
func (vq *VectorQuery) Aggregate(fns ...AggregateFunc) *VectorSelect {
	return vq.Select().Aggregate(fns...)
}

func (vq *VectorQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range vq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, vq); err != nil {
				return err
			}
		}
	}
	for _, f := range vq.ctx.Fields {
		if !vector.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vq.path != nil {
		prev, err := vq.path(ctx)
		if err != nil {
			return err
		}
		vq.sql = prev
	}
	return nil
}

func (vq *VectorQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Vector, error) {
	var (
		nodes       = []*Vector{}
		withFKs     = vq.withFKs
		_spec       = vq.querySpec()
		loadedTypes = [1]bool{
			vq.withOwner != nil,
		}
	)
	if vq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, vector.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Vector).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Vector{config: vq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, vq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := vq.withOwner; query != nil {
		if err := vq.loadOwner(ctx, query, nodes, nil,
			func(n *Vector, e *Product) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (vq *VectorQuery) loadOwner(ctx context.Context, query *ProductQuery, nodes []*Vector, init func(*Vector), assign func(*Vector, *Product)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Vector)
	for i := range nodes {
		if nodes[i].product_vectors == nil {
			continue
		}
		fk := *nodes[i].product_vectors
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(product.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "product_vectors" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (vq *VectorQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vq.querySpec()
	_spec.Node.Columns = vq.ctx.Fields
	if len(vq.ctx.Fields) > 0 {
		_spec.Unique = vq.ctx.Unique != nil && *vq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, vq.driver, _spec)
}

func (vq *VectorQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(vector.Table, vector.Columns, sqlgraph.NewFieldSpec(vector.FieldID, field.TypeInt))
	_spec.From = vq.sql
	if unique := vq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if vq.path != nil {
		_spec.Unique = true
	}
	if fields := vq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vector.FieldID)
		for i := range fields {
			if fields[i] != vector.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := vq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vq *VectorQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vq.driver.Dialect())
	t1 := builder.Table(vector.Table)
	columns := vq.ctx.Fields
	if len(columns) == 0 {
		columns = vector.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vq.sql != nil {
		selector = vq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if vq.ctx.Unique != nil && *vq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range vq.predicates {
		p(selector)
	}
	for _, p := range vq.order {
		p(selector)
	}
	if offset := vq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VectorGroupBy is the group-by builder for Vector entities.
type VectorGroupBy struct {
	selector
	build *VectorQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vgb *VectorGroupBy) Aggregate(fns ...AggregateFunc) *VectorGroupBy {
	vgb.fns = append(vgb.fns, fns...)
	return vgb
}

// Scan applies the selector query and scans the result into the given value.
func (vgb *VectorGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vgb.build.ctx, "GroupBy")
	if err := vgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VectorQuery, *VectorGroupBy](ctx, vgb.build, vgb, vgb.build.inters, v)
}

func (vgb *VectorGroupBy) sqlScan(ctx context.Context, root *VectorQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(vgb.fns))
	for _, fn := range vgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*vgb.flds)+len(vgb.fns))
		for _, f := range *vgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*vgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VectorSelect is the builder for selecting fields of Vector entities.
type VectorSelect struct {
	*VectorQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (vs *VectorSelect) Aggregate(fns ...AggregateFunc) *VectorSelect {
	vs.fns = append(vs.fns, fns...)
	return vs
}

// Scan applies the selector query and scans the result into the given value.
func (vs *VectorSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vs.ctx, "Select")
	if err := vs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VectorQuery, *VectorSelect](ctx, vs.VectorQuery, vs, vs.inters, v)
}

func (vs *VectorSelect) sqlScan(ctx context.Context, root *VectorQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(vs.fns))
	for _, fn := range vs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*vs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
