// Code generated by ent, DO NOT EDIT.

package vector

import (
	"recomCore/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Vector {
	return predicate.Vector(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Vector {
	return predicate.Vector(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Vector {
	return predicate.Vector(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Vector {
	return predicate.Vector(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Vector {
	return predicate.Vector(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Vector {
	return predicate.Vector(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Vector {
	return predicate.Vector(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Vector {
	return predicate.Vector(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Vector {
	return predicate.Vector(sql.FieldLTE(FieldID, id))
}

// Vector applies equality check predicate on the "vector" field. It's identical to VectorEQ.
func Vector(v []byte) predicate.Vector {
	return predicate.Vector(sql.FieldEQ(FieldVector, v))
}

// VectorEQ applies the EQ predicate on the "vector" field.
func VectorEQ(v []byte) predicate.Vector {
	return predicate.Vector(sql.FieldEQ(FieldVector, v))
}

// VectorNEQ applies the NEQ predicate on the "vector" field.
func VectorNEQ(v []byte) predicate.Vector {
	return predicate.Vector(sql.FieldNEQ(FieldVector, v))
}

// VectorIn applies the In predicate on the "vector" field.
func VectorIn(vs ...[]byte) predicate.Vector {
	return predicate.Vector(sql.FieldIn(FieldVector, vs...))
}

// VectorNotIn applies the NotIn predicate on the "vector" field.
func VectorNotIn(vs ...[]byte) predicate.Vector {
	return predicate.Vector(sql.FieldNotIn(FieldVector, vs...))
}

// VectorGT applies the GT predicate on the "vector" field.
func VectorGT(v []byte) predicate.Vector {
	return predicate.Vector(sql.FieldGT(FieldVector, v))
}

// VectorGTE applies the GTE predicate on the "vector" field.
func VectorGTE(v []byte) predicate.Vector {
	return predicate.Vector(sql.FieldGTE(FieldVector, v))
}

// VectorLT applies the LT predicate on the "vector" field.
func VectorLT(v []byte) predicate.Vector {
	return predicate.Vector(sql.FieldLT(FieldVector, v))
}

// VectorLTE applies the LTE predicate on the "vector" field.
func VectorLTE(v []byte) predicate.Vector {
	return predicate.Vector(sql.FieldLTE(FieldVector, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Vector {
	return predicate.Vector(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.Product) predicate.Vector {
	return predicate.Vector(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Vector) predicate.Vector {
	return predicate.Vector(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Vector) predicate.Vector {
	return predicate.Vector(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Vector) predicate.Vector {
	return predicate.Vector(func(s *sql.Selector) {
		p(s.Not())
	})
}
