// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Attribute is the predicate function for attribute builders.
type Attribute func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Rate is the predicate function for rate builders.
type Rate func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Vector is the predicate function for vector builders.
type Vector func(*sql.Selector)
